services:
  - type: web
    name: ai-url-phishing-detection
    env: python
    plan: free
    buildCommand: chmod +x build.sh && ./build.sh
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
      - key: DATABASE_URL
        fromDatabase:
          name: phishing-detection-db
          property: connectionString

databases:
  - name: phishing-detection-db
    plan: free
    databaseName: phishing_detection
    user: phishing_user
